/*
 * Template-Processor
 * <b>The Template-Processor API can generate office, xml and json documents from a template and a JSON data file. Supported templates are MS Office files and freemarker files.<</b>    The flow is generally as follows:      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sphereon.sdk.template_processor.api;

import com.sphereon.sdk.template_processor.handler.ApiException;
import com.sphereon.sdk.template_processor.model.DataSetResponse;
import com.sphereon.sdk.template_processor.model.ErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataSetApi
 */
@Ignore
public class DataSetApiTest {

    private final DataSetApi api = new DataSetApi();

    
    /**
     * Store dataset
     *
     * Upload and store a data set. Currently only JSON is supported. This call returns an id which can be specified when submitting a merge job.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDataSetTest() throws ApiException {
        String payload = null;
        DataSetResponse response = api.createDataSet(payload);

        // TODO: test validations
    }
    
    /**
     * Delete a stored data set
     *
     * Delete a stored data set
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDataSetTest() throws ApiException {
        String dataSetId = null;
        DataSetResponse response = api.deleteDataSet(dataSetId);

        // TODO: test validations
    }
    
}
