/**
 * OfficeTextMerge
 * <b>The Office Text API can generate office documents from a template and a JSON data file<</b>    The flow is generally as follows:      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OfficeTextMerge);
  }
}(this, function(expect, OfficeTextMerge) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OfficeTextMerge.MergeSettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MergeSettings', function() {
    it('should create an instance of MergeSettings', function() {
      // uncomment below and update the code to test MergeSettings
      //var instane = new OfficeTextMerge.MergeSettings();
      //expect(instance).to.be.a(OfficeTextMerge.MergeSettings);
    });

    it('should have the property lifecycle (base name: "lifecycle")', function() {
      // uncomment below and update the code to test the property lifecycle
      //var instane = new OfficeTextMerge.MergeSettings();
      //expect(instance).to.be();
    });

    it('should have the property mergeResult (base name: "mergeResult")', function() {
      // uncomment below and update the code to test the property mergeResult
      //var instane = new OfficeTextMerge.MergeSettings();
      //expect(instance).to.be();
    });

    it('should have the property dataSetId (base name: "dataSetId")', function() {
      // uncomment below and update the code to test the property dataSetId
      //var instane = new OfficeTextMerge.MergeSettings();
      //expect(instance).to.be();
    });

    it('should have the property engine (base name: "engine")', function() {
      // uncomment below and update the code to test the property engine
      //var instane = new OfficeTextMerge.MergeSettings();
      //expect(instance).to.be();
    });

    it('should have the property headerDataSetIds (base name: "headerDataSetIds")', function() {
      // uncomment below and update the code to test the property headerDataSetIds
      //var instane = new OfficeTextMerge.MergeSettings();
      //expect(instance).to.be();
    });

    it('should have the property templateVersion (base name: "templateVersion")', function() {
      // uncomment below and update the code to test the property templateVersion
      //var instane = new OfficeTextMerge.MergeSettings();
      //expect(instance).to.be();
    });

    it('should have the property resultStreamLocation (base name: "resultStreamLocation")', function() {
      // uncomment below and update the code to test the property resultStreamLocation
      //var instane = new OfficeTextMerge.MergeSettings();
      //expect(instance).to.be();
    });

    it('should have the property templateId (base name: "templateId")', function() {
      // uncomment below and update the code to test the property templateId
      //var instane = new OfficeTextMerge.MergeSettings();
      //expect(instance).to.be();
    });

    it('should have the property outputSettings (base name: "outputSettings")', function() {
      // uncomment below and update the code to test the property outputSettings
      //var instane = new OfficeTextMerge.MergeSettings();
      //expect(instance).to.be();
    });

  });

}));
