/**
 * Template-Processor
 * <b>The Template-Processor API can generate office, xml and json documents from a template and a JSON data file. Supported templates are MS Office files and freemarker files.<</b>    The flow is generally as follows:      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonTemplateProcessor/ApiClient', 'SphereonTemplateProcessor/model/OwnerInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OwnerInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.TemplateProcessor) {
      root.TemplateProcessor = {};
    }
    root.TemplateProcessor.TemplateContextRequest = factory(root.TemplateProcessor.ApiClient, root.TemplateProcessor.OwnerInfo);
  }
}(this, function(ApiClient, OwnerInfo) {
  'use strict';




  /**
   * The TemplateContextRequest model module.
   * @module SphereonTemplateProcessor/model/TemplateContextRequest
   * @version 0.1
   */

  /**
   * Constructs a new <code>TemplateContextRequest</code>.
   * The merge template request.
   * @alias module:SphereonTemplateProcessor/model/TemplateContextRequest
   * @class
   * @param templateType {module:SphereonTemplateProcessor/model/TemplateContextRequest.TemplateTypeEnum} 
   */
  var exports = function(templateType) {
    var _this = this;

    _this['templateType'] = templateType;



  };

  /**
   * Constructs a <code>TemplateContextRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:SphereonTemplateProcessor/model/TemplateContextRequest} obj Optional instance to populate.
   * @return {module:SphereonTemplateProcessor/model/TemplateContextRequest} The populated <code>TemplateContextRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('templateType')) {
        obj['templateType'] = ApiClient.convertToType(data['templateType'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('ownerInfo')) {
        obj['ownerInfo'] = OwnerInfo.constructFromObject(data['ownerInfo']);
      }
      if (data.hasOwnProperty('templateId')) {
        obj['templateId'] = ApiClient.convertToType(data['templateId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:SphereonTemplateProcessor/model/TemplateContextRequest.TemplateTypeEnum} templateType
   */
  exports.prototype['templateType'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {module:SphereonTemplateProcessor/model/OwnerInfo} ownerInfo
   */
  exports.prototype['ownerInfo'] = undefined;
  /**
   * The template context id
   * @member {String} templateId
   */
  exports.prototype['templateId'] = undefined;


  /**
   * Allowed values for the <code>templateType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TemplateTypeEnum = {
    /**
     * value: "OFFICE"
     * @const
     */
    "OFFICE": "OFFICE",
    /**
     * value: "FREEMARKER"
     * @const
     */
    "FREEMARKER": "FREEMARKER"  };


  return exports;
}));


