/**
 * Template-Processor
 * <b>The Template-Processor API can generate office, xml and json documents from a template and a JSON data file. Supported templates are MS Office files and freemarker files.<</b>    The flow is generally as follows:      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TemplateProcessor);
  }
}(this, function(expect, TemplateProcessor) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TemplateProcessor.TemplateApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TemplateApi', function() {
    describe('createTemplateContext', function() {
      it('should call createTemplateContext successfully', function(done) {
        //uncomment below and update the code to test createTemplateContext
        //instance.createTemplateContext(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTemplateContext', function() {
      it('should call deleteTemplateContext successfully', function(done) {
        //uncomment below and update the code to test deleteTemplateContext
        //instance.deleteTemplateContext(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTemplateContext', function() {
      it('should call getTemplateContext successfully', function(done) {
        //uncomment below and update the code to test getTemplateContext
        //instance.getTemplateContext(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTemplateContext', function() {
      it('should call updateTemplateContext successfully', function(done) {
        //uncomment below and update the code to test updateTemplateContext
        //instance.updateTemplateContext(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadTemplateFile', function() {
      it('should call uploadTemplateFile successfully', function(done) {
        //uncomment below and update the code to test uploadTemplateFile
        //instance.uploadTemplateFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
