/* 
 * Template-Processor
 *
 * <b>The Template-Processor API can generate office, xml and json documents from a template and a JSON data file. Supported templates are MS Office files and freemarker files.<</b>    The flow is generally as follows:      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Sphereon.SDK.TemplateProcessor.Client;
using Sphereon.SDK.TemplateProcessor.Api;
using Sphereon.SDK.TemplateProcessor.Model;

namespace Sphereon.SDK.TemplateProcessor.Test
{
    /// <summary>
    ///  Class for testing TemplateApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TemplateApiTests
    {
        private TemplateApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TemplateApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemplateApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TemplateApi
            //Assert.IsInstanceOfType(typeof(TemplateApi), instance, "instance is a TemplateApi");
        }

        
        /// <summary>
        /// Test CreateTemplateContext
        /// </summary>
        [Test]
        public void CreateTemplateContextTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TemplateContextRequest templateRequest = null;
            //var response = instance.CreateTemplateContext(templateRequest);
            //Assert.IsInstanceOf<TemplateContextResponse> (response, "response is TemplateContextResponse");
        }
        
        /// <summary>
        /// Test DeleteTemplateContext
        /// </summary>
        [Test]
        public void DeleteTemplateContextTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string templateId = null;
            //var response = instance.DeleteTemplateContext(templateId);
            //Assert.IsInstanceOf<TemplateContextResponse> (response, "response is TemplateContextResponse");
        }
        
        /// <summary>
        /// Test GetTemplateContext
        /// </summary>
        [Test]
        public void GetTemplateContextTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string templateId = null;
            //var response = instance.GetTemplateContext(templateId);
            //Assert.IsInstanceOf<TemplateContextResponse> (response, "response is TemplateContextResponse");
        }
        
        /// <summary>
        /// Test UpdateTemplateContext
        /// </summary>
        [Test]
        public void UpdateTemplateContextTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TemplateContext templateContext = null;
            //var response = instance.UpdateTemplateContext(templateContext);
            //Assert.IsInstanceOf<TemplateContextResponse> (response, "response is TemplateContextResponse");
        }
        
        /// <summary>
        /// Test UploadTemplateFile
        /// </summary>
        [Test]
        public void UploadTemplateFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string templateId = null;
            //System.IO.Stream stream = null;
            //var response = instance.UploadTemplateFile(templateId, stream);
            //Assert.IsInstanceOf<TemplateContextResponse> (response, "response is TemplateContextResponse");
        }
        
    }

}
